version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysqls_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: shakib19
      MYSQL_DATABASE: samuraiTrain
      MYSQL_PASSWORD: shakib19
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: springboot_apps
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/samuraiTrain
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: shakib19
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
